# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from signal_processing/AudioInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AudioInfo(genpy.Message):
  _md5sum = "5368011d7b904165cf3a2294c5b63f30"
  _type = "signal_processing/AudioInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 bpm # Beats per minute
float64 timestamp # Time at end of recording
uint32 top # Top part of time signature, 4 by default
uint32 bottom # Bottom part of time signature, 4 by default
"""
  __slots__ = ['bpm','timestamp','top','bottom']
  _slot_types = ['uint32','float64','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bpm,timestamp,top,bottom

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AudioInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bpm is None:
        self.bpm = 0
      if self.timestamp is None:
        self.timestamp = 0.
      if self.top is None:
        self.top = 0
      if self.bottom is None:
        self.bottom = 0
    else:
      self.bpm = 0
      self.timestamp = 0.
      self.top = 0
      self.bottom = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Id2I().pack(_x.bpm, _x.timestamp, _x.top, _x.bottom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.bpm, _x.timestamp, _x.top, _x.bottom,) = _get_struct_Id2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Id2I().pack(_x.bpm, _x.timestamp, _x.top, _x.bottom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.bpm, _x.timestamp, _x.top, _x.bottom,) = _get_struct_Id2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Id2I = None
def _get_struct_Id2I():
    global _struct_Id2I
    if _struct_Id2I is None:
        _struct_Id2I = struct.Struct("<Id2I")
    return _struct_Id2I
